### ISSUE TITLE
QST: Why does `import config` not work?

### ISSUE THREAD

**Issue by augustebaum** [pytask-dev/pytask#339]
#### Question about pytask

I created a project using a `cookiecutter` template and used `conda` to create an environment.
My project is structured as follows:
```
my_project
├── src
│   ├── __init__.py
│   ├── config.py
│   ├── tasks
│   └── my_project
├── setup.cfg
├── pyproject.toml
├── environment.yml
└── tests
```
so that `tasks` contains all the tasks and `my_project` contains all the reusable code that might be released as a package. There are `__init__.py` files in all directories within `src`.

However, when I run `pytask` in the root directory, while in my `conda` environment, collection of any task fails because `import config` fails. When I print `sys.path` I get this:
```
['<conda-env-directory>/bin',
'<conda-env-directory>/lib/python310.zip',
'<conda-env-directory>/lib/python3.10',
'<conda-env-directory>/lib/python3.10/lib-dynload',
'<conda-env-directory>/lib/python3.10/site-packages',
'<some-temp-dir>']
```

So it doesn't contain `my_project/src`. Does it make sense to anyone why this doesn't work, and how I can make it work?

In `pyproject.toml` I have:
```toml
[build-system]
requires = ["poetry-core", "setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "poetry.core.masonry.api"
```
as I used `poetry` before changing to `conda`.

In `setup.cfg` I have:
```ini
[options]
packages = find:
install_requires =
    pytask
python_requires = >=3.8
include_package_data = True
package_dir =
    =src
zip_safe = False

[options.packages.find]
where = src
```
as I didn't change anything from the `cookiecutter` template.

Any help or support would be very much appreciated. In any case, thanks for your attention and have a great day.

**Comment by tobiasraabe** [comment]
Hi @augustebaum! I have questions and notes but no definitive answer.

- What cookiecutter are you using? Did you start with https://github.com/pytask-dev/cookiecutter-pytask-project?
- I have no clue about poetry, honestly. Since it is a build system for python packages, I am unsure how it interacts with the other stuff in the configuration files like setuptools-scm.
- The settings in the `setup.cfg`, `package_dir = =src` and `where = src`, I think, require a folder in src that is the package. Your content in `src` should go into the folder `my_project/src/my_project`, and then you can import stuff from `config.py` as `from my_project.config as ...`.

If you want to be closer to the pytask cookiecutter and solve your issue, do this:

1. Remove poetry from the `pyproject.toml`.
2. Nest the content of `src` in another folder as explained above.

I hope it helps!

**Comment by augustebaum** [comment]
Thanks for the quick answer.
I trouble-shooted this with a friend and they taught me about the `pip install -e .` technique whereby you install your own codebase as a package, so that the path to `src` is included in `sys.path`. This suffices to make my tasks run properly so I'll leave it at that, but yeah my next step would have been to fit the template structure more strictly.

Thanks again!
